# Generated by Django 2.1.5 on 2020-06-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200620_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_img',
            field=models.ImageField(upload_to='figs'),
        ),
    ]
